import { exec, spawn } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import os from 'os';

const execAsync = promisify(exec);

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.join(__dirname, '..');
const PORTFOLIO_ROOT = path.join(os.homedir(), 'programming/akashramesh13.github.io');
const ASSETS_DIR = path.join(PORTFOLIO_ROOT, 'assets');
const DEST_APK_PATH = path.join(ASSETS_DIR, 'aham.apk');

async function runCommand(command, cwd) {
  console.log(`\n> Running: ${command} (in ${cwd})`);
  return new Promise((resolve, reject) => {
    const child = spawn(command, { shell: true, cwd, stdio: 'inherit' });
    child.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`Command "${command}" failed with exit code ${code}`));
      } else {
        resolve();
      }
    });
    child.on('error', (err) => {
      reject(err);
    });
  });
}

async function findNewestApkRecursive(dir) {
  let newestApk = null;
  let maxTime = 0;

  async function walk(currentDir) {
    const files = await fs.readdir(currentDir, { withFileTypes: true });
    for (const file of files) {
      const fullPath = path.join(currentDir, file.name);
      if (file.isDirectory()) {
        // Skip dependencies and source control to speed up search
        if (['node_modules', '.git', '.expo'].includes(file.name)) continue;
        await walk(fullPath);
      } else if (file.name.endsWith('.apk')) {
        const stat = await fs.stat(fullPath);
        if (stat.mtimeMs > maxTime) {
          maxTime = stat.mtimeMs;
          newestApk = fullPath;
        }
      }
    }
  }
  
  await walk(dir);
  return newestApk;
}

async function main() {
  try {
    console.log('--- Starting Android Release Workflow ---');
    
    console.log('\n[0/5] Resolving and verifying Java 17...');
    try {
      const { stdout: javaHomeStdout } = await execAsync('/usr/libexec/java_home -v 17');
      const javaHome = javaHomeStdout.trim();
      if (!javaHome) throw new Error('java_home returned empty string');
      
      process.env.JAVA_HOME = javaHome;
      process.env.PATH = `${javaHome}/bin:${process.env.PATH}`;
      console.log(`Set JAVA_HOME to: ${javaHome}`);
    } catch (e) {
      throw new Error('Failed to resolve Java 17. Please ensure it is installed.\n' + e.message);
    }

    const { stderr: javaVersionStderr } = await execAsync('java -version');
    if (!javaVersionStderr.includes('\"17.') && !javaVersionStderr.includes(' 17.')) {
      throw new Error(`Java 17 verification failed. Output:\n${javaVersionStderr}`);
    }
    console.log('Verified Java 17 successfully.');

    // 1. Execute a local Android production build
    console.log('\n[1/5] Executing local Android production build...');
    await runCommand('npm run build:android:local', PROJECT_ROOT);

    // 2. & 3. Find the generated APK automatically
    console.log('\n[2/5] Locating the generated APK...');
    const apkPath = await findNewestApkRecursive(PROJECT_ROOT);
    
    if (!apkPath) {
      throw new Error('Could not find any .apk file generated by the build.');
    }
    console.log(`Found newest APK at: ${apkPath}`);

    // 4. Copy the APK to the portfolio repository
    console.log(`\n[3/5] Copying APK to ${DEST_APK_PATH}...`);
    await fs.mkdir(ASSETS_DIR, { recursive: true });
    await fs.copyFile(apkPath, DEST_APK_PATH);
    console.log('Copy successful.');

    // 5. & 6. Change into the GitHub Pages repository and run git add
    console.log(`\n[4/5] Staging APK in portfolio repo...`);
    await runCommand('git add assets/aham.apk', PORTFOLIO_ROOT);

    // 7. & 8. Commit only if changed, and push to origin
    console.log('\n[5/5] Committing and pushing changes (if any)...');
    const { stdout } = await execAsync('git status --porcelain assets/aham.apk', { cwd: PORTFOLIO_ROOT });
    
    if (stdout.trim().length > 0) {
      console.log('APK has changed. Committing...');
      await runCommand('git commit -m "Update Aham Android APK"', PORTFOLIO_ROOT);
      
      console.log('Pushing to origin...');
      await runCommand('git push origin HEAD', PORTFOLIO_ROOT);
      console.log('Push successful.');
    } else {
      console.log('No changes detected in the APK. Skipping commit and push.');
    }

    // 9. Return to the Aham repository
    console.log('\n--- Release Workflow Completed Successfully ---');
    console.log(`Returned to Aham repository: ${PROJECT_ROOT}`);
    process.exit(0);

  } catch (error) {
    console.error('\n[!] Release Workflow Failed:');
    console.error(error.message);
    process.exit(1);
  }
}

main();
